# Generated by Django 3.1 on 2020-09-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200920_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
