# Generated by Django 3.1 on 2020-10-22 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201022_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentaccident',
            name='create_at_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
