# Generated by Django 3.1 on 2020-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201109_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentaccident',
            name='only_incident',
            field=models.CharField(choices=[('1', 'Incidente'), ('2', 'Accidente')], default='1', max_length=1),
        ),
    ]
