# Generated by Django 3.1 on 2020-11-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201126_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskreport',
            name='create_at_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
