# Generated by Django 3.1 on 2020-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200920_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreport',
            name='consequence',
            field=models.CharField(blank=True, choices=[('1', 'Improbable'), ('2', 'Remoto'), ('3', 'Ocasional'), ('4', 'Frecuente'), ('5', 'Probable')], max_length=1),
        ),
        migrations.AddField(
            model_name='riskreport',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskreport',
            name='probability',
            field=models.CharField(blank=True, choices=[('1', 'Improbable'), ('2', 'Remoto'), ('3', 'Ocasional'), ('4', 'Frecuente'), ('5', 'Probable')], max_length=1),
        ),
    ]
