# Generated by Django 3.1 on 2020-10-11 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201011_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_of_manager', to='users.smsmanager'),
        ),
    ]
