# Generated by Django 3.1 on 2020-10-22 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreport',
            name='create_at_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskreport',
            name='level_of_risk',
            field=models.CharField(blank=True, choices=[('1', 'Aceptable'), ('2', 'Moderado'), ('3', 'Alto'), ('4', 'Extremo')], max_length=1),
        ),
    ]
