# Generated by Django 3.1 on 2020-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_incidentaccident_create_at_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentaccident',
            name='only_incident',
            field=models.BooleanField(default=True),
        ),
    ]
